In [2]:
import numpy as np

x = np.array([1, 2, 3])

print(x.__class__) # 类名
print(x.shape) # 形状
print(x.ndim) # 维度

<class 'numpy.ndarray'>
(3,)
1


In [3]:
# 运算
w = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([[0, 1, 2], [3, 4, 5]])

print(w + x)

print(x * w)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [4]:
# 广播
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

c = np.array([10, 20, 30])

print(a * b)

# 维度要相同
# print(A * C)

[[10 40]
 [30 80]]


In [8]:
# 向量内积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

32


In [9]:
# 矩阵乘积
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]
